name: Build August CSV (Cloud)

on:
  workflow_dispatch: {}   # adds a "Run workflow" button
  # schedule:
  #   - cron: "0 3 1 * *"  # optional: 3:00 UTC on the 1st of every month

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build August (20–25/day, India 60–70%)
        run: |
          python build_history_csv.py \
            --month august \
            --min 20 --max 25 \
            --india-low 0.60 --india-high 0.70 \
            --include-births --include-deaths \
            --outfile august.csv

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: august-csv
          path: august.csv
